name: surf_practice_chat_flutter
description: A new Flutter project.

publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  surf_study_jam: ^0.2.0+1
  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.0.1
  bloc_concurrency: ^0.2.0
  freezed_annotation: ^2.1.0
  intl: ^0.17.0
  file_picker: ^5.0.1
  geolocator: ^9.0.1
  map_launcher: ^2.3.0+1
  flutter_svg: ^1.1.3
  flutter_list_view: ^1.1.18
  cached_network_image: ^3.2.1
  provider: ^6.0.3
  bubble: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  freezed: ^2.1.0+1
  build_runner: ^2.2.0
  analyzer: ^4.6.0

flutter:
  uses-material-design: true
